# This workflow builds and publishes Python packages to PyPI when a release is created

name: build and release

on:
  push:
    tags: release*
  workflow_run:
    workflows: ["test"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install build
        run: |
          python -m pip install build
          python -m pip install --upgrade pip setuptools wheel
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: run build
        run: python -m build --sdist
      - uses: actions/upload-artifact@v4
        with:
          path: ./dist
          if-no-files-found: error
          overwrite: true

  publish:
    name: Publish to PyPI
    environment: release
    permissions:
      id-token: write
    needs:
      - test
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: ./dist/
      - uses: pypa/gh-action-pypi-publish@release/v1
